### ISSUE TITLE
No needed anymore

### ISSUE THREAD

**Issue by oblique** [klingtnet/archlinux-4.14-thinkpad-x1-carbon-5th-gen#1]
Thanks for your package util now. In 4.14 the `rmi_smbus.c` changes were added. So instead of installing this package you can just add `psmouse.synaptics_intertouch=1` in your kernel boot parameters.

**Comment by klingtnet** [comment]
@oblique Thank you for this info, I haven't found it in the kernel's release notes.
So the Elantech touchpad works even without patching `drivers/input/mouse/synaptics.c`?

**Comment by oblique** [comment]
Yes. If you use `psmouse.synaptics_intertouch=1`  it doesn't check the `smbus_pnp_ids` array, it just continues to SMBus initialization. Check here: http://elixir.free-electrons.com/linux/v4.14/source/drivers/input/mouse/synaptics.c#L1735

**Comment by oblique** [comment]
Linux v4.14 is in `testing` repo. `LEN0073` is working fine with `psmouse.synaptics_intertouch=1`.

**Comment by klingtnet** [comment]
Thanks for the information, I can confirm that in 4.14 the Elantech touchpad works if kernel parameter `psmouse.synaptics_intertouch=1` is set.
